//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectHotels.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProjectHotels.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Change profile photo.
        /// </summary>
        internal static string AccountChangePhoto {
            get {
                return ResourceManager.GetString("AccountChangePhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Pick from gallery.
        /// </summary>
        internal static string AccountChoosePhotoGallery {
            get {
                return ResourceManager.GetString("AccountChoosePhotoGallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Take a photo.
        /// </summary>
        internal static string AccountChoosePhotoTake {
            get {
                return ResourceManager.GetString("AccountChoosePhotoTake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Choose photo.
        /// </summary>
        internal static string AccountChoosePhotoTitle {
            get {
                return ResourceManager.GetString("AccountChoosePhotoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Leave account.
        /// </summary>
        internal static string AccountLeave {
            get {
                return ResourceManager.GetString("AccountLeave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Book hotel.
        /// </summary>
        internal static string BookHotel {
            get {
                return ResourceManager.GetString("BookHotel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Dark mode.
        /// </summary>
        internal static string DarkMode {
            get {
                return ResourceManager.GetString("DarkMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Hotels added in favorites.
        /// </summary>
        internal static string FavoritesHeader {
            get {
                return ResourceManager.GetString("FavoritesHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No filters.
        /// </summary>
        internal static string FilterNone {
            get {
                return ResourceManager.GetString("FilterNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Rating higher than 8.
        /// </summary>
        internal static string FilterRating {
            get {
                return ResourceManager.GetString("FilterRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Filters.
        /// </summary>
        internal static string Filters {
            get {
                return ResourceManager.GetString("Filters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на More than 3 stars.
        /// </summary>
        internal static string FilterStars {
            get {
                return ResourceManager.GetString("FilterStars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Choose filter.
        /// </summary>
        internal static string FiltersTitle {
            get {
                return ResourceManager.GetString("FiltersTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Hotel Info.
        /// </summary>
        internal static string HotelInfoHeader {
            get {
                return ResourceManager.GetString("HotelInfoHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Hotels List.
        /// </summary>
        internal static string HotelsList {
            get {
                return ResourceManager.GetString("HotelsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Language.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Login.
        /// </summary>
        internal static string LoginButton {
            get {
                return ResourceManager.GetString("LoginButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Email:.
        /// </summary>
        internal static string LoginEmail {
            get {
                return ResourceManager.GetString("LoginEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Account isn&apos;t found. Check your data.
        /// </summary>
        internal static string LoginErrorText {
            get {
                return ResourceManager.GetString("LoginErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Account entering problem.
        /// </summary>
        internal static string LoginErrorTitle {
            get {
                return ResourceManager.GetString("LoginErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Password:.
        /// </summary>
        internal static string LoginPassword {
            get {
                return ResourceManager.GetString("LoginPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Login.
        /// </summary>
        internal static string LoginTitle {
            get {
                return ResourceManager.GetString("LoginTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Register.
        /// </summary>
        internal static string RegisterButton {
            get {
                return ResourceManager.GetString("RegisterButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Create an account.
        /// </summary>
        internal static string RegisterCreateAccount {
            get {
                return ResourceManager.GetString("RegisterCreateAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Input data is incorrect.
        /// </summary>
        internal static string RegisterCreateErrorText {
            get {
                return ResourceManager.GetString("RegisterCreateErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Accont creating problem.
        /// </summary>
        internal static string RegisterCreateErrorTitle {
            get {
                return ResourceManager.GetString("RegisterCreateErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Check email address and connection to the Internet.
        /// </summary>
        internal static string RegisterEmailErrorText {
            get {
                return ResourceManager.GetString("RegisterEmailErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Email check failure.
        /// </summary>
        internal static string RegisterEmailErrorTitle {
            get {
                return ResourceManager.GetString("RegisterEmailErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Name:.
        /// </summary>
        internal static string RegisterName {
            get {
                return ResourceManager.GetString("RegisterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Passwords do not match.
        /// </summary>
        internal static string RegisterPasswordErrorText {
            get {
                return ResourceManager.GetString("RegisterPasswordErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Repeat password.
        /// </summary>
        internal static string RegisterPasswordErrorTitle {
            get {
                return ResourceManager.GetString("RegisterPasswordErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Repeat password:.
        /// </summary>
        internal static string RegisterRepeatPassword {
            get {
                return ResourceManager.GetString("RegisterRepeatPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Create a new account.
        /// </summary>
        internal static string RegisterTitle {
            get {
                return ResourceManager.GetString("RegisterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Change account.
        /// </summary>
        internal static string SearchAccountButtonChange {
            get {
                return ResourceManager.GetString("SearchAccountButtonChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Adults.
        /// </summary>
        internal static string SearchAdults {
            get {
                return ResourceManager.GetString("SearchAdults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на City....
        /// </summary>
        internal static string SearchBarPlaceholder {
            get {
                return ResourceManager.GetString("SearchBarPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Search.
        /// </summary>
        internal static string SearchButton {
            get {
                return ResourceManager.GetString("SearchButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Children.
        /// </summary>
        internal static string SearchChildren {
            get {
                return ResourceManager.GetString("SearchChildren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Date From.
        /// </summary>
        internal static string SearchDateFrom {
            get {
                return ResourceManager.GetString("SearchDateFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Date To.
        /// </summary>
        internal static string SearchDateTo {
            get {
                return ResourceManager.GetString("SearchDateTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Search for Hotels.
        /// </summary>
        internal static string SearchDetailTitle {
            get {
                return ResourceManager.GetString("SearchDetailTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Our suggestions.
        /// </summary>
        internal static string SearchExamples {
            get {
                return ResourceManager.GetString("SearchExamples", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Account.
        /// </summary>
        internal static string SearchMenuAccount {
            get {
                return ResourceManager.GetString("SearchMenuAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Current booking.
        /// </summary>
        internal static string SearchMenuBooking {
            get {
                return ResourceManager.GetString("SearchMenuBooking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Favorites.
        /// </summary>
        internal static string SearchMenuFavorites {
            get {
                return ResourceManager.GetString("SearchMenuFavorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Search for Hotels.
        /// </summary>
        internal static string SearchMenuMain {
            get {
                return ResourceManager.GetString("SearchMenuMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Settings.
        /// </summary>
        internal static string SearchMenuSettings {
            get {
                return ResourceManager.GetString("SearchMenuSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Search result.
        /// </summary>
        internal static string SearchResult {
            get {
                return ResourceManager.GetString("SearchResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sort by.
        /// </summary>
        internal static string Sorting {
            get {
                return ResourceManager.GetString("Sorting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на By name.
        /// </summary>
        internal static string SortingName {
            get {
                return ResourceManager.GetString("SortingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на By rating.
        /// </summary>
        internal static string SortingRating {
            get {
                return ResourceManager.GetString("SortingRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на By stars.
        /// </summary>
        internal static string SortingStars {
            get {
                return ResourceManager.GetString("SortingStars", resourceCulture);
            }
        }
    }
}
